services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    Migrify\ConfigTransformer\Clarifier\:
        resource: '../src'
        exclude:
            - '../src/HttpKernel/*'

    Symplify\SmartFileSystem\Finder\FinderSanitizer: null

    Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory: null
    Symfony\Component\Console\Style\SymfonyStyle:
        factory: ['@Symplify\PackageBuilder\Console\Style\SymfonyStyleFactory', 'create']
